apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer
  namespace: default
spec:
  containers:
  - name: kafka-consumer
    image: confluentinc/cp-kafka:5.0.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
